apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oap.fullname" . }}-api
  labels:
    app: {{ include "oap.name" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ include "oap.name" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "oap.name" . }}-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          env:
            {{- range $key, $val := .Values.api.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts: []  # you were bind-mounting ../langconnect:/app in dev;
                           # in k8s you should bake code into the image instead.
