apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oap.fullname" . }}-postgres
  labels:
    app: {{ include "oap.name" . }}-postgres
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ include "oap.name" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "oap.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          env:
            {{- range $key, $val := .Values.postgres.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "oap.fullname" . }}-postgres-pvc
